name: Write Number to File

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  write-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Write number to file
        run: echo "1" > numero.txt

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Pipe codou fofamente por versão!"
 
